global CNN_tracker
Z=size(sampler.patterns_dt);
custom_f1 = single(zeros(5, 5, 3, 64));
custom_f1(:,:,1,1) = 1; 
net.params(net.getParamIndex('f1')).value = custom_f1;
net = dagnn.DagNN();
input = 'input';  
net.addLayer('conv1', ...
    dagnn.Conv('size', [5 5 3 64], 'pad', 1), ...
    {input}, {'conv1_out'}, {'f1','b1'});
net.addLayer('pool1', ...
    dagnn.Pooling('method', 'avg', 'poolSize', [3 3], 'stride', 2), ...
    {'conv1_out'}, {'pool1_out'});
net.addLayer('pool_branch1', ...
    dagnn.Pooling('method', 'avg', 'poolSize', [3 3], 'stride', 2), ...
    {'conv1_out'}, {'pool_branch1_out'});
net.addLayer('norm_branch1', ...
    dagnn.LRN('param', [4 1 1/16 0.75]), ...
    {'pool_branch1_out'}, {'norm_branch1_out'});
net.addLayer('conv2', ...
    dagnn.Conv('size', [3 3 64 96], 'pad', 1), ...
    {'pool1_out'}, {'conv2_out'}, {'f2','b2'});
net.addLayer('pool2', ...
    dagnn.Pooling('method', 'avg', 'poolSize', [2 2], 'stride', 2), ...
    {'conv2_out'}, {'pool2_out'});
net.addLayer('pool_branch2', ...
    dagnn.Pooling('method', 'avg', 'poolSize', [3 3], 'stride', 1), ...
    {'conv3_out'}, {'pool_branch2_out'});
net.addLayer('norm_branch2', ...
    dagnn.LRN('param', [2 1 1/4 0.5]), ...
    {'pool_branch2_out'}, {'norm_branch2_out'});
net.addLayer('conv3', ...
    dagnn.Conv('size', [3 3 96 128], 'pad', 1), ...
    {'pool1_out'}, {'conv2_out'}, {'f2','b2'});
net.addLayer('pool3', ...
    dagnn.Pooling('method', 'avg', 'poolSize', [3 3], 'stride', 2), ...
    {'conv2_out'}, {'pool2_out'});
net.addLayer('norm_main', ...
    dagnn.LRN('param', [1 1 1/2 0.25]), ...
    {'pool3_out'}, {'norm_main_out'});
net.addLayer('concat', ...
    dagnn.Concat('dim', 3), ...
    {'norm_main_out', 'norm_branch1_out', 'norm_branch2_out'}, ...
    {'final_output'});
